version: '3.2'

services:
 wp:
  build:
   context: ../
  restart: always
  environment:
    WORDPRESS_DEBUG: 1
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_PASSWORD: dbPassword
    WORDPRESS_DB_USER: dbUsername
  ports:
   - 8701:80
  links:
    - db:mysql
  volumes:
   - .././:/var/www/html/wp-content/plugins/termination-of-transfer
  depends_on:
    - db

 db:
  container_name: 'tot-mariadb'
  hostname: db
  image: mariadb
  restart: always
  environment:
    MARIADB_ROOT_PASSWORD: rootPassword
    MARIADB_USER: dbUsername
    MARIADB_PASSWORD: dbPassword
  volumes:
    - sql:/var/lib/mysql
  #entrypoint: mysqld_safe --skip-grant-tables --user=mysql
 
 dbsetup:
  image: mariadb
  depends_on:
    - db
  restart: "no"
  links:
    - db:mysql
  entrypoint: [ "bash", "-c", "sleep 10 && mysql -h \"db\" -p=rootPassword -u \"root\" -Be \"CREATE DATABASE IF NOT EXISTS 'wordpress'; GRANT ALL PRIVILEGES ON 'wordpress'.* TO 'dbUsername'@'%'' WITH GRANT OPTION;\""]

 phpmyadmin:
   image: phpmyadmin
   restart: always
   ports:
    - 3010:80
   links:
    - db:mysql
   environment:
    - PMA_ARBITRARY=0
    #- PMA_PORT=3006
    #- PMA_HOST=192.168.128.2
   depends_on:
    - db

volumes:
 sql: