version: '3.2'

services:
 wp:
  build:
   context: .
  restart: always
  environment:
    WORDPRESS_DEBUG: 1
    WORDPRESS_DB_HOST: 192.168.128.2
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_PASSWORD: SqlNotTooMuch
    WORDPRESS_DB_USER: codex
  ports:
   - 8701:80
  networks:
    server:
  volumes:
   - composer-fix.sh:/var/www/html/composer-fix.sh
   - ./:/var/www/html/wp-content/plugins/termination-of-transfer
  entrypoint: chmod +x composer-fix.sh && ./composer-fix.sh

 mariadb:
  image: mariadb
  restart: always
  networks:
    server:
  environment:
    MARIADB_ROOT_PASSWORD: NotTooMuch
    MARIADB_USER: codex
    MARIADB_PASSWORD: SqlNotTooMuch
  volumes:
   - sql:/var/lib/mysql
  #entrypoint: mysqld_safe --skip-grant-tables --user=mysql

 phpmyadmin:
   image: phpmyadmin
   restart: always
   ports:
    - 3010:80
   environment:
    - PMA_ARBITRARY=0
    #- PMA_PORT=3006
    - PMA_HOST=192.168.128.2
   networks:
    server:

volumes:
 sql:
networks:
  server: